 <?php
 // module/Blog/view/blog/blog/index.phtml:

 $title = 'My blog';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('blog', array('action'=>'add'));?>">Add new blog</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($blogs as $blog) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($blog->title);?></td>
     <td><?php echo $this->escapeHtml($blog->artist);?></td>
     <td>
         <a href="<?php echo $this->url('blog',
             array('action'=>'edit', 'id' => $blog->id));?>">Edit</a>
         <a href="<?php echo $this->url('blog',
             array('action'=>'delete', 'id' => $blog->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>